### ISSUE TITLE
ServerClass, SocketClass의 변경

### ISSUE THREAD

**Issue by Jack-R-lantern** [404-DriverNotFound/503-service-unavailable#2]
## 현재 클래스 디자인
**Server.hpp**
```
struct Server : public ConfigSet
{
	public:
	Socket						sock;
	std::string					server_name;
	uint16_t					port;
	std::string					auth;
	std::vector<Location>		location;
}
```
**Socket.hpp**
```
struct Socket : public sockaddr
{
	int			fd;
	socklen_t	socklen;
}
```
### **발생했던 문제점**
* socket bind를 위해 `memset`을 하던중 기존의 상관없는 데이터 요소를 침범.
* listen부분과 관련
    * Sever생성자 부분에서 `listen`호출시 에러는 발생하지 않지만 `bash`에서 `echo > /dev/tcp/<IP>/<Port>`시 에러 발생
    * server_start함수에서 호출시 `errno 38`번과 에러 메세지로 `socket operation on non-socket`
## sujung이 문제점을 해결하기 위해 변경해본것
**Server.hpp**
```
struct Server : public ConfigSet
{
	public:
	std::string					server_name;
	uint16_t					port;
	std::string					auth;
	std::vector<Location>		location;
	Socket						*sock;
}
```
**Socket.hpp
```
struct Socket
{
	int			fd;
	sockaddr_in	s_addr;
	socklen_t	socklen;
}
```
### **문제점 해결과정**
* Socket클래스를 만들때 상속이 아닌 이너 클래스 관계로 변경해봄.
    * 이와 관련해서 기존의 클래스 다지인에서 `memset`과 `reinterpret_cast`를 이용한 과정에서 메모리 컨트롤을 더 세부적으로해 기존 클래스를 활용할수 있는지 테스트해봐야함.
    * Sever클래스에 sock을 포인터 처리로 사용함으로써 스택과 힙으로 메모리를 크게 분리시도.
* listen은 Server생성자 부분, sever_start부분 두 곳중 아무곳에서나 해도  `bash`에서 `echo > /dev/tcp/<IP>/<Port>` 정상작동하는것을 확인

**Comment by pseudo-programmer42** [comment]
ok
